### ISSUE TITLE
0.1: Taller de flutter

### ISSUE THREAD

**Issue by Santlas09** [ISCOUTB/DH-InMotions#1]

**Comment by Jordy-UKQ** [comment]
Esta semana, en Flutter, aprendi que es un framework de código abierto creado por Google para desarrollar aplicaciones que funcionan tanto en dispositivos móviles, web y de escritorio, utilizando un solo código base. 

Lo más interesante de Flutter es cómo todo se basa en widgets. Estos son como las piezas fundamentales que construyen la interfaz de usuario. Cada botón, texto o contenedor en la app es un widget, y se dividen en dos tipos: stateless (sin estado, estáticos) y stateful (con estado, dinámicos), dependiendo de si necesitan cambiar en tiempo real.

Otro punto destacado es el Hot Reload, que me ha parecido increíble. Con esta función, cualquier cambio que hago en el código se refleja de inmediato en la app sin tener que reiniciar el proyecto completo. Esto hace que el proceso de desarrollo sea más ágil y eficiente.

Finalmente, me llamó la atención que Flutter incluye soporte para los estilos de diseño de Material Design de Google y Cupertino de Apple, lo que garantiza que las apps luzcan y funcionen bien tanto en Android como en iOS.

**Comment by Lxuratorres** [comment]
En el contenido proporcionado estudié lo que era Flutter, es un framework de código abierto hecho por Google para desarrollar aplicaciones móviles, web y de escritorio, usando un solo código base. Lo más interesante es que todo en Flutter se construye con widgets, que son como las piezas fundamentales de la interfaz de usuario. Estos se dividen en stateless, que no cambian, y stateful, que pueden actualizarse en tiempo real.

Una cosa que vi fue el Hot Reload, que permite ver los cambios en la app de inmediato sin reiniciarla. También tiene soporte para Material Design de Google y Cupertino de Apple, lo que hace que las apps se vean bien tanto en Android como en iOS.

**Comment by SolarKyra** [comment]
En esta semana investigue sobre creación de interfaz de usuario y widgets.

Los widgets de Flutter se construyen utilizando un marco que se inspira en Reaccionar. La idea central es que podemos crear nuestros UI a partir de widgets que están. Los widgets describen cómo debería ser su vista dada su configuración y estado actuales, también el widget reconstruye su descripción para que el marco compare con la versión anterior, identificando los cambios mínimos necesarios para actualizar el árbol de renderizado y reflejar el nuevo estado visual.
Widgets básicos

Los más comunes serian:
• Text: Permite crear una ejecución de texto con estilo dentro de su aplicación.
• Row, Column: Permiten crear diseños flexibles tanto en horizontal (Row) y vertical (Column) direcciones. El diseño de estos objetos se basa en el modelo de diseño flexbox (Flexible Box Layout) de la web.
• Stack: permite colocar widgets uno encima del otro en orden de pintura.
• Container: permite crear un elemento visual rectangular. Un contenedor puede ser decorado con un BoxDecoration, como un fondo, un borde o una sombra. A Container también puede tener márgenes, relleno y restricciones aplicadas a su tamaño. Además, a Container se puede transformar en un espacio tridimensional usando una matriz.

Muchos widgets de Diseño de materiales deben estar dentro de un MaterialApp para mostrar correctamente, para heredar los datos del tema.
MaterialApp es un widget que actúa como la base para aplicaciones que siguen el diseño de Material Design de Google. Proporciona configuraciones clave, como la navegación, temas, localización y un árbol de widgets básico para construir la interfaz de usuario de la aplicación.
Navegator es un widget que administra un conjunto de widgets secundarios con una disciplina de pila. También gestiona una pila de widgets identificados por cadenas, también conocidas como "rutas". El Navigator le permite hacer una transición sin problemas entre las pantallas de su aplicación.

**Comment by Santlas09** [comment]
En Flutter, la construcción de interfaces de usuario se basa en el uso de widgets, que son bloques de construcción reutilizables que describen cómo debería verse la aplicación. Los widgets pueden ser de dos tipos principales: StatelessWidget, que representa una interfaz de usuario inmutable, y StatefulWidget, que puede cambiar su estado y reconstruirse en respuesta a eventos del usuario o cambios de datos. Flutter utiliza un sistema eficiente para actualizar la interfaz de usuario, reconstruyendo solo las partes del árbol de widgets que han cambiado. Esta arquitectura permite una gran flexibilidad en el diseño de aplicaciones, facilitando la creación de interfaces ricas e interactivas. Además, Flutter ofrece herramientas para manejar la disposición de widgets mediante contenedores como Row, Column, y Stack, permitiendo así la creación de layouts complejos de manera sencilla y eficiente.
