### ISSUE TITLE
1.4.1: Diseñar una interfaz para mostrar los registros anteriores.

### ISSUE THREAD

**Issue by SolarKyra** [ISCOUTB/DH-InMotions#10]

**Comment by Santlas09** [comment]
![Image](https://github.com/user-attachments/assets/f6de302e-2d92-452a-9f4b-7385ca8e4c80)

muestra implementada y en progreso

**Comment by Lxuratorres** [comment]
**Registros anteriores de emociones**
En el diseño se puede observar el calendario emocional, donde se puede agregar y tener un seguimiento de cómo se ha estado el ánimo del usuario, se guarda con fecha y hora de ingreso. Como opciones de emociones se tiene: feliz, neutral, decaído, triste y enojado.
