### ISSUE TITLE
0.3: Definir wireframes de toda la aplicacion

### ISSUE THREAD

**Issue by Santlas09** [ISCOUTB/DH-InMotions#3]

**Comment by Lxuratorres** [comment]
Inicio de sesion, el usuario podrá ingresar con su cuenta o de lo contrario crear una
![Image](https://github.com/user-attachments/assets/ce4c1a01-4b11-4346-af59-d4e7a05f6c46)
Crear cuenta, en caso tal el usuario no tenga cuenta, se podrá crear una
![Image](https://github.com/user-attachments/assets/67fe8388-b92c-4446-999c-f7ab7a6b61b9)
El usuario ingresará y se encontrará con el inicio, podrá anotar y hacer seguimiento de su día y sus emociones
![Image](https://github.com/user-attachments/assets/7d60ccbf-430f-45b8-a0d9-456799ee7f70)

**Comment by jairoserrano** [comment]
adelante
