### ISSUE TITLE
1.1.2: Implementar la lógica para seleccionar y guardar la opción elegida.

### ISSUE THREAD

**Issue by SolarKyra** [ISCOUTB/DH-InMotions#5]

**Comment by Santlas09** [comment]
Añadido al codigo fuente: ![Image](https://github.com/user-attachments/assets/4b80577d-b6e2-4928-9f47-a144b985f052)

**Comment by Lxuratorres** [comment]
**Seleccionar y guardar la opción elegida**
Este código permite al usuario escribir una nota en un **TextField**, seleccionar una emoción, y al presionar el botón "Guardar", guarda esa información (junto con el correo del usuario) en algún gestor de datos **(UserDataManager**). Luego, se muestra una notificación indicando que la emoción fue guardada, y el campo de texto se limpia.
