### ISSUE TITLE
1.2.2: Desarrollar la lógica para guardar la nota junto con el estado de ánimo.

### ISSUE THREAD

**Issue by SolarKyra** [ISCOUTB/DH-InMotions#6]

**Comment by Jordy-UKQ** [comment]
Recibe los datos: El backend recibe los datos enviados desde el frontend a través de una solicitud HTTP POST.
Validación: Verifica que la nota y el estado de ánimo no estén vacíos.
Almacenar en MongoDB: Guarda la nota y el estado de ánimo junto con la fecha en que fueron creados en una colección de MongoDB.

![Image](https://github.com/user-attachments/assets/380206e8-d080-45a6-b02d-8573dbeb202d)

**Comment by jairoserrano** [comment]
prioricen UI/UX
