### ISSUE TITLE
1.3.1: Implementar una función que capture automáticamente la fecha y hora del registro.

### ISSUE THREAD

**Issue by SolarKyra** [ISCOUTB/DH-InMotions#8]

**Comment by Santlas09** [comment]
Añadido al codigo fuente: ![Image](https://github.com/user-attachments/assets/b69723d9-dc96-4d0d-9898-f5a2660417ad)

**Comment by Lxuratorres** [comment]
**Captura de la fecha y hora de registro**
Este código define un calendario interactivo en la interfaz. Muestra las fechas desde el año 2000 hasta el 2100. El formato del calendario (mes, semana, etc.) puede cambiar, y cuando lo hace, se actualiza el estado de la UI para reflejar el nuevo formato seleccionado por el usuario.
